# improve colors
set -g default-terminal 'tmux-256color'

# set a tiny non-zero esc time: https://github.com/LunarVim/LunarVim/issues/1857#issuecomment-1175912906
set -sg escape-time 10

# allow passthrough: https://tmuxai.dev/tmux-allow-passthrough/
set -g allow-passthrough on
set -g set-clipboard on  # Enable OSC 52 clipboard
set -ga terminal-features ",xterm-256color:RGB"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"
# set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(),}"
set -g @catppuccin_directory_text " #T"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g  status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# Override status bar background for transparency (must be after plugin load)
set -g status-bg default
set -g status-style bg=default

# enable mouse mode
set-option -g mouse on

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# copy - paste
bind-key -n -T copy-mode-vi Enter send-keys -X copy-pipe 'xclip -i -sel p -f | xclip -i -sel c'
bind-key -n -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'xclip -i -sel p -f | xclip -i -sel c'

# start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set-window-option -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

# increase scrollback lines
set -g history-limit 10000

# record history to a file
set -g history-file ~/.tmux_history

# don't suspend-client
unbind-key C-z

# open in cwd when splitting
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# open new window in cwd
#bind c new-window -c "#{pane_current_path}"
# capital C opens in cwd
bind C new-window -c "#{pane_current_path}"

# ctrl-b = resizes main pane to take 3/4 of the screen width
bind -r = resizep -t"{left}" -x "75%"
