# Enable HW acceleration
hwdec=auto-safe

# Hide window border.
no-border

# Do not close the window on exit.
keep-open=yes

# launch within the available screen space.
autofit-larger=100%x100%

# Minimum window size
autofit-smaller=800x600

# Set default volume and disable overamplification
volume=100
volume-max=100

script-opts=ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"

# Max 1080p30 for YouTube videos. Also avoid vp9 video codec.
ytdl-format=bestvideo[height<=?1080][fps<=?30][vcodec!=?vp9]+bestaudio/best
