[preferred]
default=wlr;gtk;

###
# Fix for Firefox not activating idle-inhibit taken from https://www.reddit.com/r/swaywm/comments/1dqud2a/how_to_get_firefox_to_inhibit_idle_when_watching/

# ignore inhibit because gtk portal always returns as success,
# despite sway/the wlr portal not having an implementation,
# stopping firefox from using wayland idle-inhibit
org.freedesktop.impl.portal.Inhibit=none
